{application,comeonin,
             [{config_mtime,1729332001},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"A specification for password hashing libraries"},
              {modules,['Elixir.Comeonin',
                        'Elixir.Comeonin.BehaviourTestHelper',
                        'Elixir.Comeonin.PasswordHash']},
              {registered,[]},
              {vsn,"5.5.0"}]}.
