{application,rewrite,
             [{config_mtime,1729332001},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,mix,crypto,glob_ex,
                             sourceror]},
              {description,"An API for rewriting sources in an Elixir project. Powered by sourceror."},
              {modules,['Elixir.Enumerable.Rewrite','Elixir.Rewrite',
                        'Elixir.Rewrite.Application','Elixir.Rewrite.Error',
                        'Elixir.Rewrite.Filetype','Elixir.Rewrite.Source',
                        'Elixir.Rewrite.Source.Ex',
                        'Elixir.Rewrite.SourceError',
                        'Elixir.Rewrite.SourceKeyError',
                        'Elixir.Rewrite.TextDiff',
                        'Elixir.Rewrite.UpdateError']},
              {registered,[]},
              {vsn,"0.10.5"},
              {mod,{'Elixir.Rewrite.Application',[]}}]}.
