{application,phoenix_view,
             [{config_mtime,1729332001},
              {optional_applications,[phoenix_html]},
              {applications,[kernel,stdlib,elixir,eex,phoenix_html,
                             phoenix_template]},
              {description,"The view layer in Phoenix v1.0-v1.6 apps"},
              {modules,['Elixir.Phoenix.Template.UndefinedError',
                        'Elixir.Phoenix.View']},
              {registered,[]},
              {vsn,"2.0.4"}]}.
