defmodule Example.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project1) do
      add :total_sales, :bigint
    end
  end

  def down do
    alter table(:project1) do
      remove :total_sales
    end
  end
end
