defmodule Example.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:labels, primary_key: false) do
      add :project_id, :uuid, null: false, primary_key: true
      add :field_1, :bigint
      add :field_2, :bigint
      add :field_3, :bigint
      add :field_4, :bigint
      add :field_5, :bigint
      add :field_6, :bigint
      add :field_7, :bigint
    end
  end

  def down do
    drop table(:labels)
  end
end
