defmodule Example.Repo.Migrations.MigrateResources17 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projectgeneral) do
      add :is_freezed, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:projectgeneral) do
      remove :is_freezed
    end
  end
end
