defmodule Example.Repo.Migrations.MigrateResources12 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:labels) do
      add :field_8, :text
      add :field_9, :text
      add :field_10, :text
      add :field_11, :text
      add :field_12, :text
      add :field_13, :text
      add :field_14, :text
      add :field_15, :text
      add :field_16, :text
      add :field_17, :text
      add :field_18, :text
      add :field_19, :text
      add :field_20, :text
    end
  end

  def down do
    alter table(:labels) do
      remove :field_20
      remove :field_19
      remove :field_18
      remove :field_17
      remove :field_16
      remove :field_15
      remove :field_14
      remove :field_13
      remove :field_12
      remove :field_11
      remove :field_10
      remove :field_9
      remove :field_8
    end
  end
end
