defmodule Example.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:labels) do
      modify :field_7, :text
      modify :field_6, :text
      modify :field_5, :text
      modify :field_4, :text
      modify :field_3, :text
      modify :field_2, :text
      modify :field_1, :text
    end
  end

  def down do
    alter table(:labels) do
      modify :field_1, :bigint
      modify :field_2, :bigint
      modify :field_3, :bigint
      modify :field_4, :bigint
      modify :field_5, :bigint
      modify :field_6, :bigint
      modify :field_7, :bigint
    end
  end
end
