defmodule Example.Repo.Migrations.MigrateResources13 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("labels", "labels_pkey")

    alter table(:labels) do
      modify :project_id, :uuid, primary_key: false
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end
  end

  def down do
    drop constraint("labels", "labels_pkey")

    alter table(:labels) do
      remove :id
      modify :project_id, :uuid, primary_key: true
    end
  end
end
