defmodule Example.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project1) do
      add :field_7, :bigint
    end
  end

  def down do
    alter table(:project1) do
      remove :field_7
    end
  end
end
