defmodule Example.Repo.Migrations.MigrateResources15 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:registry) do
      add :days_worked, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:registry) do
      remove :days_worked
    end
  end
end
