defmodule Example.Repo.Migrations.MigrateResources14 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:registry, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :project_id, :uuid, null: false
      add :ambassador_id, :uuid, null: false
      add :outlet_id, :uuid, null: false
    end
  end

  def down do
    drop table(:registry)
  end
end
