defmodule Example.Activation.Promoter do
  use Ash.Resource,
    # Tells Ash where the generated code interface belongs
    domain: Example.Activation,
    data_layer: AshPostgres.DataLayer

  resource do
    description """
    Represents the Brand Ambassadors
    Handles the Sensitive information belonging to a Brand Ambassador
    """

    plural_name :promoters
    short_name :promoter
  end

  postgres do
    table "promoters"
    repo Example.Repo
  end

  # Attributes are simple pieces of data that exist in your resource
  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id

    attribute :name, :string do
      allow_nil? false
    end

    attribute :id_num, :integer do
      allow_nil? false
    end
  end

  actions do
    # Exposes default built in actions to manage the resource
    defaults [:read, :destroy]

    create :create do
      # accept name as input
      # * accept behaves like cast/3 in ecto changesets
      accept [:name, :id_num]
    end

    update :update do
      # accept content as input
      accept [:id_num]
    end

    # Defines custom read action which fetches post by id.
    read :by_id do
      # This action has one argument :id of type :uuid
      argument :id, :uuid, allow_nil?: false
      # Tells us we expect this action to return a single result
      get? true
      # Filters the `:id` given in the argument
      # against the `id` of each element in the resource
      filter expr(id == ^arg(:id))
    end
  end
end
