{application,websock_adapter,
             [{config_mtime,1729332001},
              {optional_applications,[bandit,plug_cowboy]},
              {applications,[kernel,stdlib,elixir,websock,plug,bandit,
                             plug_cowboy]},
              {description,"A set of WebSock adapters for common web servers"},
              {modules,['Elixir.WebSockAdapter',
                        'Elixir.WebSockAdapter.UpgradeError',
                        'Elixir.WebSockAdapter.UpgradeValidation']},
              {registered,[]},
              {vsn,"0.5.7"}]}.
